/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TagEditor.java
 *
 * Created on May 6, 2011, 1:43:28 PM
 */
package org.ensor.robots.editor.editors;

import org.ensor.robots.editor.objects.TagDef;

import org.ensor.tools.editor.base.IEditor;
import org.ensor.data.atom.*;
import org.ensor.tools.editor.base.GameEditorBase;
/**
 *
 * @author Jon
 */
public class EditorTagDef extends javax.swing.JPanel implements IEditor {
    private TagDef              mTagDef;
    
    /** Creates new form ImageEditor */
    public EditorTagDef(GameEditorBase geb) {
        initComponents();
        mTagDef = new TagDef();
    }
    
    @Override
    public void read(DictionaryAtom aDict) {
        mTagDef.read(aDict);
    }

    @Override
    public DictionaryAtom write() {
        return mTagDef.write();
    }
    @Override
    public boolean validateContent() {
        return true;
    }
    
    @Override
    public javax.swing.JPanel getPanel() {
        return this;
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
