/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComponentTextField.java
 *
 * Created on Jun 25, 2011, 1:17:28 PM
 */
package org.ensor.tools.editor.base.components;

import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author Jon
 */
public class ComponentTextField extends javax.swing.JPanel {

    ComponentTextFieldEventHandler          mHandler;
    
    /** Creates new form ComponentTextField */
    public ComponentTextField() {
        initComponents();
        mHandler = null;
        
        mTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                if (mHandler != null) mHandler.onTextChanged(mTextField.getText());
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                if (mHandler != null) mHandler.onTextChanged(mTextField.getText());
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                if (mHandler != null) mHandler.onTextChanged(mTextField.getText());
            }
        });
    }
    
    public String getText() {
        return mTextField.getText();
    }
    public void setText(String aValue) {
        mTextField.setText(aValue);
    }
    
    public void setTextFieldHandler(ComponentTextFieldEventHandler aHandler) {
        mHandler = aHandler;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mTextField = new javax.swing.JTextField();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField mTextField;
    // End of variables declaration//GEN-END:variables
}
