/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ensor_robots_sensors_kinect_Driver */

#ifndef _Included_org_ensor_robots_sensors_kinect_Driver
#define _Included_org_ensor_robots_sensors_kinect_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ensor_robots_sensors_kinect_Driver
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_org_ensor_robots_sensors_kinect_Driver_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     org_ensor_robots_sensors_kinect_Driver
 * Method:    nativeShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ensor_robots_sensors_kinect_Driver_nativeShutdown
  (JNIEnv *, jobject);

/*
 * Class:     org_ensor_robots_sensors_kinect_Driver
 * Method:    nativeDeviceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ensor_robots_sensors_kinect_Driver_nativeDeviceCount
  (JNIEnv *, jobject);

/*
 * Class:     org_ensor_robots_sensors_kinect_Driver
 * Method:    nativeSetLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ensor_robots_sensors_kinect_Driver_nativeSetLogLevel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
