/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ensor_robots_sensors_kinect_Device */

#ifndef _Included_org_ensor_robots_sensors_kinect_Device
#define _Included_org_ensor_robots_sensors_kinect_Device
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ensor_robots_sensors_kinect_Device
 * Method:    nativeOpen
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_org_ensor_robots_sensors_kinect_Device_nativeOpen
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ensor_robots_sensors_kinect_Device
 * Method:    nativeClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ensor_robots_sensors_kinect_Device_nativeClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ensor_robots_sensors_kinect_Device
 * Method:    nativeStopVideo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ensor_robots_sensors_kinect_Device_nativeStopVideo
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ensor_robots_sensors_kinect_Device
 * Method:    nativeStartVideo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ensor_robots_sensors_kinect_Device_nativeStartVideo
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ensor_robots_sensors_kinect_Device
 * Method:    nativeStopDepth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ensor_robots_sensors_kinect_Device_nativeStopDepth
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ensor_robots_sensors_kinect_Device
 * Method:    nativeStartDepth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ensor_robots_sensors_kinect_Device_nativeStartDepth
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ensor_robots_sensors_kinect_Device
 * Method:    nativeSetLED
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_ensor_robots_sensors_kinect_Device_nativeSetLED
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_ensor_robots_sensors_kinect_Device
 * Method:    nativeSetTiltDegrees
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_ensor_robots_sensors_kinect_Device_nativeSetTiltDegrees
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_ensor_robots_sensors_kinect_Device
 * Method:    nativeGetState
 * Signature: (ILorg/ensor/robots/sensors/kinect/ITiltListener;)V
 */
JNIEXPORT void JNICALL Java_org_ensor_robots_sensors_kinect_Device_nativeGetState
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
